## Invoices [/invoices]

### /getInvoices.php [POST /getInvoices.php]

Search invoices

+ Request (application/json)

    + Attributes (object)
        + date_from: `01/01/2017` (string, required) - Format: dd/mm/yyyy
        + date_to: `31/12/2017` (string, required) - Format: dd/mm/yyyy
        + contact_or_company: `contact` (enum[string], optional) - Use this to filter by client
            + Members
                + contact
                + company
        + contact_or_company_id: `1` (number, optional) - ID of the contact or company
        + deep_search: `1` (number, optional) Pass 1 to return not just invoices related to the requested contact, but also to invoices related to linked companies
        + selected_customfields: `1,2` (string, optional) - comma-separated list of the IDs of the custom fields you wish to select (max 10).

+ Response 200 (application/json)

    + Attributes (array[Invoice])

### /getCreditnotes.php [POST /getCreditnotes.php]

Search creditnotes

+ Request (application/json)

    + Attributes (object)
        + `date_from`: `01/01/2017` (string, required) - Format: dd/mm/yyyy
        + `date_to`: `31/12/2017` (string, required) - Format: dd/mm/yyyy
        + contact_or_company: `contact` (enum[string], optional) - Use this to filter by client
            + Members
                + contact
                + company
        + contact_or_company_id: `1` (number, optional) - ID of the contact or company
        + deep_search: `1` (number, optional) Pass 1 to return not just invoices related to the requested contact, but also to invoices related to linked companies

+ Response 200 (application/json)

    + Attributes (array[Creditnote])

### /getInvoicesByProject.php [POST /getInvoicesByProject.php]

Search invoices

+ Request (application/json)

    + Attributes (object)
        + project_id: `1` (number, required) - ID of the project
        + include_draft_invoices: `1` (number, optional) -  set this parameter to 1 to include draft invoices
            + Default: `0`

+ Response 200 (application/json)

    + Attributes (array[Invoice])

### /getCreditnotesByProject.php [POST /getCreditnotesByProject.php]

Search creditnotes

+ Request (application/json)

    + Attributes (object)
        + project_id: `1` (number, required) - ID of the project
        + include_draft_invoices: `1` (number, optional) -  set this parameter to 1 to include draft invoices
            + Default: `0`

+ Response 200 (application/json)

    + Attributes (array[Creditnote])

### /getInvoiceCloudURL.php [POST /getInvoiceCloudURL.php]

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (number, required) - ID of the invoice

+ Response 200 (application/json)

    + Attributes (object)
        + invoice_nr: `2017 / 8` (string)
        + invoicecloud_secret_url: `http://dev.invoicecloud.be/?invoice_id=1&gid=1&token=Gg8oUwLf9EmzS7Wxkr0L2fT6kgcBuXO04NeO9QT9l5y43lseCiPvnzryFuZ0` (string)
        + invoicecloud_secret: `Gg8oUwLf9EmzS7Wxkr0L2fT6kgcBuXO04NeO9QT9l5y43lseCiPvnzryFuZ0` (string)

### /getBookkeepingAccounts.php [POST /getBookkeepingAccounts.php]

+ Request (application/json)

    + Attributes (object)
        + sys_department_id: `1` (number, required) - ID of the department 

+ Response 200 (application/json)

    + Attributes (array)
        + id: `1` (number)
        + account: `70000` (number)
        + name_nl: `general account` (string)
        + name_fr: `account general` (string)
