## Invoices [/invoices]

### /getInvoices.php [POST /getInvoices.php]

Search invoices

+ Request (application/json)

    + Attributes (object)
        + date_from: `01/01/2017` (string, required) - Format: dd/mm/yyyy
        + date_to: `31/12/2017` (string, required) - Format: dd/mm/yyyy
        + contact_or_company: `contact` (enum[string], optional) - Use this to filter by client
            + Members
                + contact
                + company
        + contact_or_company_id: `1` (number, optional) - ID of the contact or company
        + deep_search: `1` (number, optional) Pass 1 to return not just invoices related to the requested contact, but also to invoices related to linked companies
        + selected_customfields: `1,2` (string, optional) - comma-separated list of the IDs of the custom fields you wish to select (max 10).

+ Response 200 (application/json)

    + Attributes (array[Invoice])

### /getCreditnotes.php [POST /getCreditnotes.php]

Search creditnotes

+ Request (application/json)

    + Attributes (object)
        + `date_from`: `01/01/2017` (string, required) - Format: dd/mm/yyyy
        + `date_to`: `31/12/2017` (string, required) - Format: dd/mm/yyyy
        + contact_or_company: `contact` (enum[string], optional) - Use this to filter by client
            + Members
                + contact
                + company
        + contact_or_company_id: `1` (number, optional) - ID of the contact or company
        + deep_search: `1` (number, optional) Pass 1 to return not just invoices related to the requested contact, but also to invoices related to linked companies

+ Response 200 (application/json)

    + Attributes (array[Creditnote])

### /getInvoicesByProject.php [POST /getInvoicesByProject.php]

Search invoices

+ Request (application/json)

    + Attributes (object)
        + project_id: `1` (number, required)
        + include_draft_invoices: `1` (number, optional) -  set this parameter to 1 to include draft invoices
            + Default: `0`

+ Response 200 (application/json)

    + Attributes (array[Invoice])

### /getCreditnotesByProject.php [POST /getCreditnotesByProject.php]

Search creditnotes

+ Request (application/json)

    + Attributes (object)
        + project_id: `1` (number, required)
        + include_draft_invoices: `1` (number, optional) -  set this parameter to 1 to include draft invoices
            + Default: `0`

+ Response 200 (application/json)

    + Attributes (array[Creditnote])

### /sendInvoice.php [POST /sendInvoice.php]

Send booked invoices via email. A maximum of 10 attachments can be provided.

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (number, required) - ID of the invoice or credit note you want to render to PDF
        + email_to: `info@teamleader.eu,support@teamleader.eu` (string, required) - Use a comma separated list to send the email to a maximum of 5 addresses.
        + email_subject: `Reminder to pay invoice` (string, required)
        + email_text: `Please pay your invoice` (string, required)
        + attachment_filename_1: `attachment1.pdf` (string, optional) - filename for the attachment
        + attachment_base64_content_1: `asdfsdfsdf...` (string, optional) - Base64 encoded file contents

+ Response 200 (application/json)

    + Attributes (object)
        + status: `success` (string) - Indicating success or failure of the operation.

### /getInvoiceReminderTemplates.php [POST /getInvoiceReminderTemplates.php]

Get the id and name of available email reminder templates for an invoice

+ Request (application/json)

    + Attributes (object)
        + invoice_id: `1` (number, required) - ID of the invoice or credit note you want to view available reminders for
        
+ Response 200 (application/json)

    + Attributes (object)
        + status: `success` (string) - Indicating success or failure of the operation.

+ Response 200 (application/json)

    + Attributes (object)
        + status: `success` (string) - Indicating success or failure of the operation.
        + data: (array)
            + (object)
                + id: `1` (number)
                +name: `template1` (string)
