## Meetings [/meetings]

### /deleteMeeting.php [POST /deleteMeeting.php]

Delete a meeting from Teamleader

+ Request (application/json)

    + Attributes (object)
        + id: `1` (number, required) - The ID of the meeting you wish to delete

+ Response 204
