## Meetings [/meetings]

### /delete.php [POST /delete.php]

Delete a meeting from Teamleader

+ Request (application/json)

    + Attributes (object)
        + meeting_ID: `1` (number, required) - The ID of the meeting you wish to delete

+ Response 204
