## Meetings [/meetings]

### /getMeeting.php [POST /getMeeting.php]

Get a detailed overview of a single meeting.

+ Attributes (Meeting)

+ Request (multipart/form-data)

    + Body
        {
            `meeting_id`: 1
        }

+ Response 200 (aplication/json)

    {
        "id": 1,
        "title": "Meeting X",
        "duration_minutes": 60,
        "date_timestamp": 554774400,
        "date_day": "01/08/1987",
        "date_hour": "12:00",
        "attending_internal": [
            {
                "contact_id": 1,
                "name": "name",
                "gsm": "0123 45 67 89",
                "telephone": "012 23 45 67",
                "email": "info@example.com"
            }
        ],
        "attending_external": [
            {
                "contact_id": 1,
                "name": "name",
                "gsm": "0123 45 67 89",
                "telephone": "012 23 45 67",
                "email": "info@example.com"
            }
        ],
        "creator_id": 1,
        "canceller_id": 1,
        "location": "Street 1, B-1234 City",
        "location_detailed": {
            "type": "type",
            "contact": 1,
            "company": 1
        },
        "project_id": 1,
        "milestone_id": 1,
        "date_added": 554774400,
        "date_added_formatted": "01/08/1987 00:00",
        "related_sale_id": 1 ,
        "custom_fields" : [],
        "description": "Description of meeting."
    }
