## Subscriptions [/subscriptions]

### /addSubscription.php [POST /addSubscription.php]

Add subscription

+ Request (application/json)

    Item lines can be added by giving the item line ID as suffix. eg description_1 will contain the description for Item line 1, description_2 will contain the description for item line 2, ...

    + Attributes(object)
        + contact_or_company: `contact` (enum[string], required) - Who is the subscription for?
            + Members
                + contact
                + company
        + contact_or_company_id: `1` (number, required) - ID of the contact or company
        + sys_department_id: `1` (number, required) - ID of the department the invoice will be added to
        + date_start: `01/08/1987` (string, required) - Date the first invoice should be created. The date should be in the format dd/mm/yyyy
        + repeat_after: `monthly` (enum[string], required) - Repeat cycle 
            + Members
                + monthly
                + quarterly
                + yearly
                + sixmonthly
                + twomonthly
                + twoyearly
                + 3yearly
                + 4yearly
                + 5yearly
                + twoweekly
                + 6yearly
                + 7yearly
                + 8yearly
                + 9yearly
                + 10yearly
                + fourmonthly
        + title: `Monthly subscription Teamleader` (string, required) - eg: Hosting, Domain names,...
        + date_end: `01/08/1987` (string, optional) - Date this subscription should expire. Date should be in the format dd/mm/yyyy
        + related_deal_id: `1` (number, optional) - ID of the deal this subscription is related to
        + permanent_invoicing: `0` (enum[number], optional) - Default 1.
            + Members
                + 0 - Do not automatically book subscription.
                + 1 - Automatically book subscription.
        + autosend_invoice: `0` (enum[number], optional) - Automatically send subscription invoice
            + Members
                + 0 - Do not send subcription invoice automatically.
                + 1 - Sends subscription invoice automatically.
        + autosend_bpost: `0` (enum[number], optional) - Automatically send subscription invoice through phsyical mail.
            + Members
                + 0 - Do not send subscription invoice through physical mail
                + 1 - Send subscription invoice through physical mail automatically.
        + comments: `Comment` (string, optional) - Comments
        + days_in_advance: `1` (number, optional) - Sending of the invoice. Set to 0 to send out the invoice on the day it's due. Defaults to 7 days
        + payment_term: `0D` (enum[string], optional) - Default: 30D
            + Members
                + 0D
                + 7D
                + 10D
                + 15D
                + 21D
                + 30D
                + 45D
                + 60D
                + 30DEM
                + 60DEM
                + 90DEM
        + custom_field_ID: `bar` (string, optional) - Replace ID by the ID of your custom field. (eg custom_field_310)
        + description_ID: `Item description` (string, optional) - Description of item line ID
        + price_ID: `12.34` (number, optional) - Item line ID price
        + amount_ID: `100` (number, optional) - Item line ID amount
        + vat_ID: `00` (enum[string], optional) - The vat tariff for item line ID
            + Members
                + 00
                + 06
                + 12
                + 21
                + CM
                + EX
                + MC
                + VCMD
        + product_ID_1: `1` (number, optional) - Id of the product for item line ID
        + account_ID: `1` (number, optional) - Id of the bookkeeping account for item line ID
        + subtitle_ID: `Sub sub title` (string, optional) - Subtitle for item line ID

+ Response 200 (application/json)
    + Attributes (object)
        + id: `416654` (number) - ID of the subscription that was added

### /updateSubscription.php [POST /updateSubscription.php]

    Update subscription

+ Request (application/json)

    + Attributes
        + subscription_id: `1` (number, required) - ID of the subscription
        + date_start: `01/08/1987` (string, optional) - Date the first invoice should be created. The date should be in the format dd/mm/yyyy.
        + repeat_after: `monthly` (enum[string], optional) -  Invoice repeat cycle
            + Members
                + monthly
                + quarterly
                + yearly
                + sixmonthly
                + twomonthly
                + twoyearly
                + 3yearly
                + 4yearly
                + 5yearly
                + twoweekly
                + 6yearly
                + 7yearly
                + 8yearly
                + 9yearly
                + 10yearly
                + fourmonthly
        + custom_field_ID: `bar` (string, optional) - Replace ID by the ID of your custom field. (eg custom_field_310)

+ Response 200 (application/json)
    + Attributes (object)
        + status: `success` (string)

### /deleteSubscription.php [POST /deleteSubscription.php]

    Delete subscription

+ Request (application/json)

    + Attributes
        + subscription_id: `1` (number, required) - ID of the subscription

+ Response 200 (application/json)
    + Attributes (object)
        + status: `success` (string)

### /getSubscription.php [POST /getSubscription.php]

    Find single subscription

+ Request (application/json)

    + Attributes
        + subscription_id: `1` (number, required) - ID of the subscription

+ Response 200 (application/json)

    + Attributes
        + id: `1` (number) - ID of the subscription
        + active: `0` (enum[number]) - Subscription status.
            + members
                + 0
                + 1
        + title: `Subscription title` (string) - Title
        + repeat: `monthly` (enum[string], required) - Invoice repeat cycle 
            + Members
                + monthly
                + quarterly
                + yearly
                + sixmonthly
                + twomonthly
                + twoyearly
                + 3yearly
                + 4yearly
                + 5yearly
                + twoweekly
                + 6yearly
                + 7yearly
                + 8yearly
                + 9yearly
                + 10yearly
                + fourmonthly
        + department_id: `1` (number) - ID of the department
        + date_start: `554774400` (number) - Start date of subscription as unix timestamp
        + date_start_formatted: `01/08/1987` (string) - Start date of subscritpion in formatted string mm/dd/yyyy.
        + date_end: `554774400` (number) -  End date of subscription as unix timestamp
        + date_end_formatted: `01/08/1987` (string) - End date of subscritpion in formatted string mm/dd/yyyy.
        + total_price_excl_vat: `12.34` (number) - Price excl VAT
        + total_price_incl_vat: `12.34` (number) - Price incl VAT
        + next_renewal_date: `554774400` (number) - Next renewal date of subscription as unix timestamp
        + next_renewal_date_formatted: `01/08/1987` - (string) Next renewal date of subscritpion in formatted string mm/dd/yyyy.
        + items: [] (array[object]) - Item line
            + (object)
                + text: `title` (string) - Title
                + amount: `1` (number) - Item amount
                + line_total_incl_vat `12.34` (number) - Line incl VAT
                + line_total_excl_vat `12.34` (number) - Line excl VAT
                + vat_rate `21` (number) - VAT rate
                + account `1` (number) - Account ID
                + subtitle `Line subtitle` (string) - Subtitle for line
                + description `Line description` (string) - Description for line
        + for: `contact` (enum[string], required) - Who is the subscription for?
            + Members
                + contact
                + company
        + for_id: `1` (number) - ID of the related contact or company
        + custom_fields: [] (array) - Array containing the id's of the custom fields and their values


### /getSubscriptions.php [POST /getSubscriptions.php]

    Search subscriptions

+ Request (application/json)

    + Attributes(object)
        + amount: `50` (number, required) - The amount of subscriptions returned per request (between 1 and 100)
        + pageno: `0` (number, required) - The page number (the first page is 0)
        + selected_customfields: `14,15` (array[number]) - Comma-separated list of the IDs of the custom fields you wish to select (max 10)
        + searchby: `teamleader` (string) - We'll try to match each part of the string to the subscription title and content

+ Response 200 (application/json)

    + Attributes (array)
        + (object)
            + id: `48100` (number) - The id of the subscription
            + active: `1` (enum[number]) - Boolean indicating if the invoice is active
                + Members
                    + 1
                    + 0
            + repeat: `quarterly` (enum[string])
                + Members
                    + monthly
                    + quarterly
                    + yearly
                    + sixmonthly
                    + twomonthly
                    + twoyearly
                    + 3yearly
                    + 4yearly
                    + 5yearly
                    + twoweekly
                    + 6yearly
                    + 7yearly
                    + 8yearly
                    + 9yearly
                    + 10yearly
                    + fourmonthly
            + client_name: `Erlich Bachman` (string) - Name of the client
            + department_name: `Finance` (string) - Department for which the subscription is created
            + department_id: `2` (number) - Id of the department
            + date_start: `1480287600` (number) - Unix timestamp of the start date of the subscription
            + date_start_formatted: `28/11/2016` (string) - Formatted start date of the subscription
            + date_end `1480287600` (number, nullable) - Unix timestamp of the end date of the subscription (can be empty)
            + date_end_formatted `28/11/2016` (string, nullable) - Formatted end date of the subscription
            + total_price_excl_vat: `100.00` (number) - Price, excluding VAT
            + total_price_incl_vat: `106.00` (number) - Price, including VAT
            + next_renewal_date: `1488236400` (number) - Unix timestamp of the next renewal date
            + next_renewal_date_formatted: `28/02/2017` - Formatted next renewal date
            + contact_or_company: `contact` (enum[string]) - Indicates the subscription is linked to a contact or a company
                + Members
                    + contact
                    + company
            + contact_or_company_id: `1174438` (number) - The id of the contact or company
            

### /getInvoicesBySubscription.php [POST /getInvoicesBySubscription.php]

    Fetching the IDs of all invoices created by a subscription

+ Request (application/json)

    + Attributes(object)
        + subscription_id: `1245` (number, required) - The id of the subscription

+ Response 200 (application/json)

    + Attributes(object)
        + generated_invoice_ids: `11400, 11401` (array[number])

### /getRelatedSubscriptionsByInvoice.php [POST /getRelatedSubscriptionsByInvoice.php]

    Fetching the IDs of all subscriptions related to an invoice

+ Request (application/json)

    + Attributes(object)
        + invoice_id: `1471` (number, required) - The id of the invoice

+ Response 200 (application/json)

    + Attributes(array)
        + (object)
            + subscription_id: `7457` (number)
            + subscription_title: `Monthly subscription Teamleader` (string)

### /getSubscriptionsByDeal.php [POST /getSubscriptionsByDeal.php]

    Fetching the IDs of all subscriptions related to a deal

+ Request (application/json)

    + Attributes(object)
        + deal_id: `1337` (number, required) - The id of the deal

+ Response 200 (application/json)

    + Attributes(object)
        + related_subscription_ids: `1245, 2584` (array[number])

### /getSubscriptionsByContactOrCompany.php [POST /getSubscriptionsByContactOrCompany.php]

    Fetching all subscripions related to a contact or company

+ Request (application/json)

    + Attributes(object)
        + contact_or_company: `contact` (enum[string], required) - State 'what' you are searching for, a contact or a company
            + Members
                + contact
                + company
        + contact_or_company_id: `1234` (number, required) - The id of the contact or the company 

+ Response 200 (application/json)

    + Attributes(array)
        + (object)
            + id: `1247` (number)
