## Subscriptions [/subscriptions]

### /addSubscription.php [POST /addSubscription.php]

Add subscription

+ Request (application/json)

+ Response 200 (text/html)

### /updateSubscription.php [POST /updateSubscription.php]

    Update subscription

+ Request (application/json)

+ Response 200 (text/html)

### /deleteSubscription.php [POST /deleteSubscription.php]

    Update subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscription.php [POST /getSubscription.php]

    Find single subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscriptions.php [POST /getSubscriptions.php]

    Search subscriptions

+ Request (application/json)

+ Response 200 (application/json)

### /getInvoicesBySubscription.php [POST /getInvoicesBySubscription.php]

    Find all subscriptions related to an invoice

+ Request (application/json)

+ Response 200 (application/json)

### /getRelatedSubscriptionsByInvoice.php [POST /getRelatedSubscriptionsByInvoice.php]

    subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscriptionsByDeal.php [POST /getSubscriptionsByDeal.php]

    subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscriptionsByContactOrCompany.php [POST /getSubscriptionsByContactOrCompany.php]

    subscription

+ Request (application/json)

+ Response 200 (application/json)

