## Subscriptions [/subscriptions]

### /addSubscription.php [POST /addSubscription.php]

Add subscription

+ Request (application/json)

+ Response 200 (text/html)

### /updateSubscription.php [POST /updateSubscription.php]

    Update subscription

+ Request (application/json)

+ Response 200 (text/html)

### /deleteSubscription.php [POST /deleteSubscription.php]

    Update subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscription.php [POST /getSubscription.php]

    Find single subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscriptions.php [POST /getSubscriptions.php]

    Search subscriptions

+ Request (application/json)

+ Response 200 (application/json)

### /getInvoicesBySubscription.php [POST /getInvoicesBySubscription.php]

    Find all subscriptions related to an invoice

+ Request (application/json)

+ Response 200 (application/json)

### /getRelatedSubscriptionsByInvoice.php [POST /getRelatedSubscriptionsByInvoice.php]

    subscription

+ Request (application/json)

+ Response 200 (application/json)

### /getSubscriptionsByDeal.php [POST /getSubscriptionsByDeal.php]

    Fetching all subscriptions related to a deal

+ Request (application/json)

    + Attributes(object)
        + deal_id: 1337 (number, required) - The id of the deal

+ Response 200 (application/json)

    + Attributes(array)
        + (object)
            + id: 7457 (number)

### /getSubscriptionsByContactOrCompany.php [POST /getSubscriptionsByContactOrCompany.php]

    Fetching all subscripions related to a contact or company

+ Request (application/json)

    + Attributes(object)
        + contact_or_company: contact (enum[string], required) - State 'what' you are searching for, a contact or a company
            + Members
                + contact
                + company
        + contact_or_company_id: 1234 (number, required) - The id of the contact or the company 

+ Response 200 (application/json)

    + Attributes(array)
        + (object)
            + id: 1247 (number)
