## Teams [/teams]

### /getTeams.php [POST /getTeams.php]

Get all teams

+ Request (application/json)

+ Response 200 (application/json)

### /getTeam.php [POST /getTeam.php]

+ Request (application/json)

+ Response 200 (application/json)
