# Group Timetracking

## Timetracking [/timetracking]

### /addTimetracking.php [POST /addTimetracking.php]

+ Request (application/x-www-form-urlencoded)

    Additional cost can be added with optional params. These params are suffixed with the index (1 based) of the
    additional cost  (`<param>_<index_of_additional_cost>`).
    So the description of the first additional cost will be `description_1` and `description_2` for the second
    additional cost.

    + Attributes
        + description: description (string) - Description of the activity
        + start_date: `1498048402` (number) - Start date of the activity as Unix timestamp (seconds)
        + end_date: `1498048402` (number) - End date of the activity as Unix timestamp (seconds)
        + worker_id: `12` (number) - Id of the user
        + task_type_id: `13` (number) - Type id of the task
        + for: company (enum[string], optional) - Who this activity should be billed to
            + Members
                + contact
                + company
                + project_milestone
        + for_id: `1` (number, optional) - The id of who this activity should be billed to
        + invoiceable: `0` (enum[number], optional) - Can this time be invoiced later or not? This parameter has no effect for project-related timetracking, because invoiceability is determined by the related milestone.
            + Members
                + 0
                + 1
        + subtract_break: `1` (enum[number], optional) - If this parameter is set to 1 lunchbreaks will be substracted from the timetracking
             + Members
                 + 0
                 + 1
        + related_object_type: task (enum[string], optional) - What kind of item this activity is related to
            + Members
                + none
                + task
        + related_object_id: `1` (number, optional) - If this activity is related to a task, pass in the task ID
        + description_1: description (string, optional) - Additional costs description
        + price_1: `100` (number, optional) - Additional cost price
        + amount_1: `100` (number, optional) - Additional cost amount
        + vat_1: `06` (enum[string], optional) - The vat tariff for this line for the additional cost
            + Members
                + 00
                + 06
                + 12
                + 21
                + CM
                + EX
                + MC
                + VCMD
        + product_id_1: `1` (number, optional) - Id of the product for the additional cost
        + subtitle_1: subtitle (string, optional) - Additional cost subtitle

+ Response 200 (text/html)

    + Body

         "OK"


### /updateTimetracking.php [POST /updateTimetracking.php]

+ Request (application/x-www-form-urlencoded)

    Additional cost can be added with optional params. These params are suffixed with the index (1 based) of the
    additional cost  (`<param>_<index_of_additional_cost>`).
    So the description of the first additional cost will be `description_1` and `description_2` for the second
    additional cost.

    + Attributes
        + timetracking_id: `1` (number) - ID of the timetracking to update
        + description: description (string, optional) - Description of the activity
        + start_date: `1498048402` (number, optional) - Start date of the activity as Unix timestamp (seconds)
        + end_date: `1498048402` (number, optional) - End date of the activity as Unix timestamp (seconds)
        + worker_id: `12` (number, optional) - Id of the user
        + task_type_id: `13` (number, optional) - Type id of the task
        + for: company (enum[string], optional) - Who this activity should be billed to
            + Members
                + contact
                + company
                + project_milestone
        + for_id: `1` (number, optional) - The id of who this activity should be billed to
        + invoiceable: `0` (enum[number], optional) - Can this time be invoiced later or not? This parameter has no effect for project-related timetracking, because invoiceability is determined by the related milestone.
            + Members
                + 0
                + 1
        + subtract_break: `1` (enum[number], optional) - If this parameter is set to 1 lunchbreaks will be substracted from the timetracking
             + Members
                 + 0
                 + 1
        + related_object_type: task (enum[string], optional) - What kind of item this activity is related to
            + Members
                + none
                + task
        + related_object_id: `1` (number, optional) - If this activity is related to a task, pass in the task ID
        + description_1: description (string, optional) - Additional costs description
        + price_1: `100` (number, optional) - Additional cost price
        + amount_1: `100` (number, optional) - Additional cost amount
        + vat_1: `06` (enum[string], optional) - The vat tariff for this line for the additional cost
            + Members
                + 00
                + 06
                + 12
                + 21
                + CM
                + EX
                + MC
                + VCMD
        + product_id_1: `1` (number, optional) - Id of the product for the additional cost
        + subtitle_1: subtitle (string, optional) - Additional cost subtitle

+ Response 200 (text/html)

    + Body

         "OK"


### /getTimetrackingEntry.php [GET /getTimetrackingEntry.php]

+ Request (application/x-www-form-urlencoded)

    + Attributes
        + timetracking_id: `1` (number) - The id of the timetracking entry

+ Response (text/html)

    + Attributes
        + id: `98` (number) - Id of the timetracking
        + user_id: `1` (number) -
        + employee_name: `Jane Doe` (string) -
        + date: `1452553200` (number) -
        + date_formatted: `dd/mm/yyyy` (string) -
        + duration: `5` (number) -
        + contact_id: `2` (number) -
        + company_id: `3` (number) -
        + project_id: `4` (number) -
        + project_title: `Title` (string) -
        + description: `Description` (string) -
        + milestone_id: `5` (number) -
        + milestone_title `Title` (string) -
        + ticket_id: `6` (number) -
        + is_invoicable: `true` (boolean)
        + related_to (object)
            + object_type: `none` (string)
            + object_id: `1` (number)

    + Body

                 [
                     {
                         "id": 98,
                         "user_id": 1,
                         "employee_name": "Jane Doe",
                         "date": 1452553200,
                         "date_formatted": "12\/01\/2016",
                         "duration": 1440,
                         "contact_id": "",
                         "company_id": "",
                         "project_id": "",
                         "project_title": "",
                         "milestone_id": "",
                         "milestone_title": "",
                         "description": "test",
                         "ticket_id": "",
                         "is_invoiceable": 0,
                         "related_to": {
                             "object_type": "none",
                             "object_id": ""
                         }
                     }
                 ]
